"""initial schema

Revision ID: 1c75a4f9f403
Revises: 
Create Date: 2026-01-11 12:01:15.262183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c75a4f9f403'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False, comment='Tenant unique identifier'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Property/building name'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-friendly identifier (e.g., 'sunset-towers')"),
    sa.Column('subscription_tier', sa.String(length=50), server_default='basic', nullable=False, comment='Subscription plan (basic, pro, enterprise)'),
    sa.Column('settings', sa.JSON(), server_default='{}', nullable=False, comment='Tenant-specific settings and preferences (JSON)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp (NULL if active)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='User unique identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (unique per tenant)'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Argon2id password hash (NULL for social/SSO users)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full name"),
    sa.Column('unit_number', sa.String(length=50), nullable=True, comment='Unit/apartment number for tenant users'),
    sa.Column('phone_number', sa.String(length=50), nullable=True, comment='User phone number'),
    sa.Column('role', sa.Enum('TENANT_USER', 'PROPERTY_ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False, comment='User role in the system'),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False, comment='Whether email has been verified'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether user account is active'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Last successful login timestamp'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant (property) identifier for multi-tenancy'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
