"""add vms tables

Revision ID: 3bf47ea2e383
Revises: 89cbb0e3011e
Create Date: 2026-03-14 16:49:19.602720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf47ea2e383'
down_revision: Union[str, Sequence[str], None] = '89cbb0e3011e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant (property) identifier for multi-tenancy'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_email'), 'visitors', ['email'], unique=False)
    op.create_index(op.f('ix_visitors_tenant_id'), 'visitors', ['tenant_id'], unique=False)
    op.create_index('uq_visitors_tenant_email', 'visitors', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'checked_in', 'checked_out', 'cancelled', name='visitstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant (property) identifier for multi-tenancy'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_tenant_id'), 'visits', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_visits_visitor_id'), 'visits', ['visitor_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('sent_to_email', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'viewed', 'expired', name='invitationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant (property) identifier for multi-tenancy'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_tenant_id'), 'invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_visit_id'), 'invitations', ['visit_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'websocket', name='notificationchannel'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant (property) identifier for multi-tenancy'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_visit_id'), 'notifications', ['visit_id'], unique=False)
    op.create_table('qr_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('one_time', 'time_bounded', name='qrcodetype'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant (property) identifier for multi-tenancy'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_qr_codes_tenant_id'), 'qr_codes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_visit_id'), 'qr_codes', ['visit_id'], unique=False)
    # ### end Alembic commands ###

    # Enable RLS on all new tables
    for table in ["visitors", "visits", "qr_codes", "invitations", "notifications"]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id::text = current_setting('app.current_tenant_id', TRUE))
            WITH CHECK (tenant_id::text = current_setting('app.current_tenant_id', TRUE))
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop RLS policies before dropping tables
    for table in ["notifications", "invitations", "qr_codes", "visits", "visitors"]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_codes_visit_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_tenant_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index(op.f('ix_notifications_visit_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invitations_visit_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_tenant_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_visits_visitor_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_tenant_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index('uq_visitors_tenant_email', table_name='visitors', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_visitors_tenant_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_email'), table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###

    # Drop named enum types that were created with the tables
    op.execute("DROP TYPE IF EXISTS visitstatus")
    op.execute("DROP TYPE IF EXISTS invitationstatus")
    op.execute("DROP TYPE IF EXISTS qrcodetype")
    op.execute("DROP TYPE IF EXISTS notificationchannel")
    op.execute("DROP TYPE IF EXISTS notificationstatus")
